### ISSUE TITLE
magic_partial fails for a class

### ISSUE THREAD

**Issue by BrentSouza** [meadsteve/lagom#129]
Not sure if intentional, but I had a need for using `Container.magic_partial` on a class type as opposed to a function. This throws an error because it's not able to resolve any of the dependencies.

Taking a look at the pathway for `Container.resolve`, I noticed that it reflects on `__init__` whereas `magic_partial` reflects directly on the callable:

https://github.com/meadsteve/lagom/blob/70127078149c2d209fef8ec229937acb9fa3f03f/lagom/container.py#L384

vs

https://github.com/meadsteve/lagom/blob/70127078149c2d209fef8ec229937acb9fa3f03f/lagom/container.py#L319

I was able to patch this by checking if `func` is a function or not:

```python
if isinstance(func, types.FunctionType):
    spec = self._reflector.get_function_spec(func)
else:
    spec = self._reflector.get_function_spec(func.__init__)
```

Which works successfully with something like:

```python
class Foo:
    def greet(self) -> str:
        return "Hello Foo"

class Bar:
    def __init__(self, not_injected: str, foo: foo) -> None:
        self.not_injected = not_injected
        self.foo = foo

    def greet(self) -> str:
        return self.foo.greet() + self.not_injected

container = Container()
container[Foo] = Foo()
bar = c.magic_partial(Bar)(not_injected="!")
bar.greet()
```

I can open a pull request with the fix above, just wanted to check if this was a design decision first.

Also, thanks for your work on the library!

**Comment by meadsteve** [comment]
@BrentSouza This is in the category of "accidental design decision". I'd only really intended `partial` and `magic_partial` for use with functions. Let me have a think about this and I'll get back to you. 

Thanks for input and I hope the library has been useful for you.

**Comment by meadsteve** [comment]
So I've thought about it and I don't see any downside to adding this. So PR welcome 👍. I think we'd want the same behaviour in partial as well for consistency

**Comment by BrentSouza** [comment]
Nice. Makes sense regarding `partial`. I'll submt a PR for both shortly
