### ISSUE TITLE
Injection into instance methods

### ISSUE THREAD

**Issue by LeafyLappa** [meadsteve/lagom#161]
Hi!

Strangely I'm unable to make DI work with async / await coroutines as instance methods. Codes:
```Python3
import asyncio
from lagom import Container, injectable
class Foo: pass
class Bar: pass
class CoroutineHolder:
    async def coroutine(self, foo: Foo = injectable, bar: Bar = injectable):
        print(foo)
        print(bar)
container = Container()
holder = CoroutineHolder()
coroutine_with_deps = container.partial(holder.coroutine)
asyncio.run(coroutine_with_deps())
# prints the following:
# <lagom.markers.Injectable object at 0x0000026A36369FD0>
# <lagom.markers.Injectable object at 0x0000026A36369FD0>
```

I inspected into the code a little (I'm not a great python programmer) and it seems ```Container._get_spec_without_self(self, func: Callable[..., X])``` errs when the ```func``` argument is a Coroutine:

```Python3
if isinstance(func, FunctionType):
    spec = self._reflector.get_function_spec(func)
else:
    t = cast(Type[X], func)
    spec = self._reflector.get_function_spec(t.__init__).without_argument(
        "self"
    )
return spec
```

Coroutines are [CoroutineType](https://docs.python.org/3/library/types.html#types.CoroutineType) unrelated to FunctionType, so this function makes a call to `__init__`, perhaps that is why, or I'm doing something wrong 😄

**Comment by LeafyLappa** [comment]
Indeed if I set `spec` to `self._reflector.get_function_spec(func)` in runtime using debugger everything works!

**Comment by LeafyLappa** [comment]
Ultimately subclassing Container and overriding `_get_spec_without_self` works for me. I guess this issue can be considered resolved.

**Comment by meadsteve** [comment]
thanks for raising this @LeafyLappa . Most of the time I've used injection into classes and plain functions but the code you've provided should work. I'll investigate this further.

**Comment by meadsteve** [comment]
I've fixed this in the upcoming version of lagom. Thanks again for the detailed report @LeafyLappa
