### ISSUE TITLE
Support class based endpoints in Starlette

### ISSUE THREAD

**Issue by espositofulvio** [meadsteve/lagom#166]
Hello,
I tried to look up for a similar issue, but couldn't find anything relevant. Is there support for class based endpoints in the Starlette integration? For API having a resource represented as an HTTPEndpoint is quite natural and it would be useful to support this use case.
A quick example I wrote failed and I can see why (sterlette endpoints are actually asgi apps that internally route the requests based on the method, so the app callable signature is different from a function endpoint).

**Comment by meadsteve** [comment]
@espositofulvio this is definitely a missing feature. I don't see any reason why this couldn't be added.
