### ISSUE TITLE
Injecting instances with a __call__ method on the class

### ISSUE THREAD

**Issue by bejoygm** [meadsteve/lagom#206]
One of the use case is to Inject an instance of [HttpBearer](https://github.com/tiangolo/fastapi/blob/44d1b21ba2e7e1b5a3f1190ee122a77c12271067/fastapi/security/http.py#L100) in FastAPI routes

since the instance will have a different type than the class definition itself, this doesn't inject the instance as a dependency. Is there a workaround? Thanks

**Comment by meadsteve** [comment]
@bejoygm Have you got a short code snippet that doesn't work correctly so I can get my head around this?

**Comment by meadsteve** [comment]
My instinct is that with HttpBearer it makes more sense to make your code depend on thing it needs `HTTPAuthorizationCredentials` and then have something like:

```python

container[HTTPAuthorizationCredentials] = lambda c: c[HttpBearer](c[Request])
```

**Comment by bejoygm** [comment]
@meadsteve here's one of the ways

`from fastapi import Depends
from fastapi.security import HTTPBearer

@router.get("")
async def get_something(
    auth_token=Depends(HTTPBearer()),  # noqa
):
    pass`
you can find similar examples [here](https://fastapi.tiangolo.com/advanced/security/oauth2-scopes/#oauth2-security-scheme)

**Comment by meadsteve** [comment]
So I've not tested it but the way I would write something like that with lagom would be:

```python
from fastapi import Depends
from fastapi.security import HTTPBearer


container = Container()
deps = FastApiIntegration(container)

container[HTTPAuthorizationCredentials] = lambda: HTTPBearer()

@router.get("")
async def get_something(
    auth_token= deps.depends(HTTPAuthorizationCredentials)
):
    pass
```

One of the goals of lagom was to make code work well with type checking so that  deps.depends(X) will always return an instance of X.

**Comment by bejoygm** [comment]
```python
container[HTTPAuthorizationCredentials] = lambda: HTTPBearer()()
```
☝️ This would have worked I guess but the HTTPBearer object's `__call__` takes a request parameter. Pasting the code here for ref.
```python
async def __call__(self, request: Request) -> Optional[HTTPAuthorizationCredentials]:
        authorization: str = request.headers.get("Authorization")
        scheme, credentials = get_authorization_scheme_param(authorization)
        if not (authorization and scheme and credentials):
            if self.auto_error:
                raise HTTPException(status_code=HTTP_403_FORBIDDEN, detail="Not authenticated")
            else:
                return None
...
```

I tried passing the request parameter explicitly, but the injected object is not correct (in both cases, a coroutine object)
```python
container[HTTPBearer] = lambda: HTTPBearer()
container[HTTPAuthorizationCredentials] = lambda c: c[HttpBearer](c[Request])
```
```python
container[HTTPAuthorizationCredentials] = lambda request: HTTPBearer()(request)
```

**Comment by meadsteve** [comment]
🤦 I totally missed that HTTPBearer is an async `__call__` I'll need to rework my suggestion

**Comment by meadsteve** [comment]
So the "simple" solution is to tweak the above to:

```python
container[HTTPBearer] = Singleton(lambda: HTTPBearer())
container[Awaitable[HTTPAuthorizationCredentials]] = lambda c: c[HTTPBearer](c[Request])

@router.get("")
async def get_something(
    auth_token= deps.depends(Awaitable[HTTPAuthorizationCredentials])
):
    await auth_token
```

but I'm a bit hesitant to suggest this as if auth_token is not `await`ed then the auth logic is skipped.

**Comment by bejoygm** [comment]
with the explicit await, the generated docs will not have the token documented properly. Anyways, I think it is not a big issue. I can always use fastAPI `Depends` for this stuff.
We have started using lagom at other places for dep injection and it is a joy to work with. Thanks for the library! 🙌

**Comment by meadsteve** [comment]
@bejoygm thank you that's really nice to hear. And using the fastapi one sounds like the best approach here 👍 especially for anything related to security/auth.
