### ISSUE TITLE
Question: Pass command line arguments to FastAPI / Starlette to create a DI (Singleton)

### ISSUE THREAD

**Issue by dineshbvadhia** [meadsteve/lagom#230]
I want to pass command line arguments to create a Singleton (or a DI in FastAPI terminology) for the duration of the service. Each endpoint (route) needs access to the Singleton. In the illustrative (non-working) code below the command line argument (s: str) is transformed into the thisobj object which is then made available to all endpoints.

How can lagom be used to solve this problem?
```
from fastapi import FastAPI, Depends, Request

class ThisObj:
    def __init__(self, thing: str) -> None:
        self.thing = thing

# Want to pass CLI arguments to on_startup here
async def on_startup() -> None:
    app.state.thisobj = ThisObj(s)

app = FastAPI(on_startup=[on_startup])

def get_thisobj(request: Request) -> ThisObj:
    return request.app.state.thisobj

@app.get("/")
async def index(thisobj: ThisObj = Depends(get_thisobj)) -> None:
    assert isinstance(thisobj, ThisObj)
    assert thisobj.thing == s

def main(args):
    params: list[str] = args[2].split()
    s: str = params[0]

    uvicorn.run('main:app', host="127.0.0.1", port=8000, reload=True)

if __name__ == "__main__":
    main(sys.argv)
```

**Comment by dineshbvadhia** [comment]
Close

**Comment by meadsteve** [comment]
@dineshbvadhia did you find an answer to your question? It sounds like you are looking for https://lagom-di.readthedocs.io/en/latest/framework_integrations/#request-level-singletons
