### ISSUE TITLE
Pydantic v2 update

### ISSUE THREAD

**Issue by rickythefox** [meadsteve/lagom#245]
With Pydantic v2 out and FastAPI having migrated to it I think Lagom might want to upgrade.

**Comment by meadsteve** [comment]
@rickythefox Have you run into problems working with lagom + pydantic v2? The `Env` module was built using pydantic 1 so that definitely needs an upgrade but everything else *should* work.

**Comment by rickythefox** [comment]
That's the one I was referring to. I can submit a pr if you want.

**Comment by meadsteve** [comment]
@rickythefox I'd love a PR if you've got the time.

**Comment by meadsteve** [comment]
Released as version 2.5.0 (no need for a major bump as I added an extra fix so that pydantic v1 is still supported)
