### ISSUE TITLE
Question Can you use ContextManagers without using the decorator?

### ISSUE THREAD

**Issue by ShravanSunder** [meadsteve/lagom#256]
Is it possible to use context managers without decorators?  https://lagom-di.readthedocs.io/en/latest/clean_up/

**Comment by meadsteve** [comment]
@ShravanSunder it is possible as lagom will construct them like any other types but the consuming code will need to make sure they are used within a `with` block. The reason for the decorators above is to automatically bind the decorated function to the with block. 

So the example in the docs without the special context container and decorator would look like this:

```python
@bind_to_container(container)
def do_something(dep_manage: ContextManager[SomeDep] = injectable):
    with dep_manager as dep:
        print(f"I got {dep}")
```
