### ISSUE TITLE
Lagom doesn't seemt to recognize default values during injection

### ISSUE THREAD

**Issue by ShravanSunder** [meadsteve/lagom#257]
```
class PromptTemplateRepo(BaseRepo):
  def __init__(self, *, sa_service: SaService | None = None, should_auto_commit: bool = False):
    super().__init__(sa_service=sa_service, should_auto_commit=should_auto_commit)
```

```
repo = agent_store_container()[PromptTemplateRepo]
```

UnresolvableType: Unable to construct dependency of type 
PromptTemplateRepo The constructor probably has some 
unresolvable dependencies: PromptTemplateRepo => bool => 
bool

I would have expected it to take into account default values during injection.  @meadsteve any thoughts on if i should restructure my class or is this a bug with lagom?

**Comment by Enforcer** [comment]
I think it's an example of undefined behaviour.

Handing defaults might be a nice add-on.

**Comment by meadsteve** [comment]
I always intended this to work but it looks like I didn't cover this exact situation with a test. Let me take a look and see if it has a quick fix.

**Comment by meadsteve** [comment]
It was. At least for the simple case. I've got a PR for this. I'll do some more testing and aim to release this in the next few days
