### ISSUE TITLE
Considering using Lagom for a work project

### ISSUE THREAD

**Issue by GavanWilhite** [meadsteve/lagom#64]
Any chance we can chat for a bit on the future of the project / ask some questions about how to architect a Lagom application?

(If email works for you, I'm gavan(at)wilhite.io )

**Comment by meadsteve** [comment]
sure 👍  I'll send you an email

**Comment by meadsteve** [comment]
@GavanWilhite hopefully my email didn't land in spam. Let me know if you've still got any questions.
